[template]

src = "nginx.conf.tmpl"
dest = "/etc/nginx.conf"
# dest = "tmp/nginx.conf"
# prefix = "/docker/machines"
keys = [ "/docker/machines" ]
owner = "root"
mode = "0644"
check_cmd = "/usr/local/sbin/nginx -t"
reload_cmd = "/usr/local/sbin/nginx -s reload"
